esphome:
  name: dininglamp
  friendly_name: DiningLamp

esp8266:
  board: esp12e
  restore_from_flash: true

external_components:
  - source: github://Szabka/ehcomp
    components: [rgbp] 

# Enable logging
logger:
  baud_rate: 921600
  level: debug

# Enable Home Assistant API
api:
  reboot_timeout: 0s
ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "DiningRoom-Lamp Hotspot"
    password: !secret ap_password

captive_portal:

#web_server:
#  port: 80

output:
  - platform: esp8266_pwm
    pin: GPIO4
    id: cool_pin
    frequency: 1000 Hz
    min_power: 0.01
    zero_means_zero: true
  - platform: esp8266_pwm
    pin: GPIO12
    id: warm_pin
    frequency: 1000 Hz
    min_power: 0.01
    zero_means_zero: true
  - platform: esp8266_pwm
    pin: GPIO13
    id: red_pin
    frequency: 1000 Hz
  - platform: esp8266_pwm
    pin: GPIO15
    id: green_pin
    frequency: 1000 Hz
  - platform: esp8266_pwm
    pin: GPIO5
    id: blue_pin
    frequency: 1000 Hz

power_supply:
  - id: power_rgb
    pin: GPIO14
    keep_on_time: 1s

light:
  - platform: cwww
    name: "Main Light"
    cold_white: cool_pin
    warm_white: warm_pin
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 3000 K
    restore_mode: RESTORE_DEFAULT_ON
  - platform: rgbp
    name: "RGB Light"
    red: red_pin
    green: green_pin
    blue: blue_pin
    power_supply: power_rgb
    restore_mode: RESTORE_DEFAULT_OFF

